### ISSUE TITLE
dev: inspect references (external)

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#272] opened 2018-04-25 15:35 UTC
If I click on inspect references to see the crossref reference list, I can't go back to the to do list. I just see an empty page with the header. I can't click anything and have to load the startpage again.
![emptypage](https://user-images.githubusercontent.com/32642653/39256359-fdfd5b72-48ae-11e8-9c6f-ec778eda82a0.png)
What's going on?

**Comment by lgalke** [comment] 2018-04-25 15:38
Hm, that is strange, gave it a try and : 
https://locdb.bib.uni-mannheim.de/extrapolate-dev/linking/RefsInspector/5ab4c0fa09398b026b4c6888
works fine. Could you copy the URL from the browser in here?

**Comment by anlausch** [comment] 2018-04-25 15:40
Sorry, I deleted the test data you uploaded. You might need to create the scenario again.

**Comment by LauraErhard** [comment] 2018-04-25 15:43
@lgalke if I click your link I only get:

`The requested URL /extrapolate-dev/linking/RefsInspector/5ab4c0fa09398b026b4c6888 was not found on this server.
Apache/2.4.25 (Debian) Server at locdb.bib.uni-mannheim.de Port 443`

**Comment by lgalke** [comment] 2018-04-25 15:47
That's expected, and related to #203 .
The error itself could be caused by the suggestions. We should first exclude that
```_co.newResource is null"``` does not cause troubles @chah3d

**Comment by lgalke** [comment] 2018-04-25 15:53
The empty page should just not happen, we will check tomorrow. The one `newResource is null` error should be resolved already now. This could help already, but not guaranteed.

**Comment by lgalke** [comment] 2018-04-26 07:44
Please try again after a52ce6e97a1cfafe789f78f93b7e3a862311bb34

**Comment by lgalke** [comment] 2018-04-26 12:02
Should be resolved by now, regarding the editing of entries we continue in #273

**Closed by lgalke** 2018-04-26 12:02 UTC
Labels: dev, testing
