### ISSUE TITLE
Open citations types

### ISSUE THREAD

**Issue by SylviaZander** [locdb/locdb-frend#175] opened 2017-11-14 14:33 UTC
As mentioned in the issue #146 we need additional resources types. Do you know when you can implement the types?
For the different types we need different fields,e.g. 
1. Journal
new fields:
ZDB-ID (SWB-field 2110, MARC21 016)
fields not needed: 
edition, number

2. article
new fields: 
issue, volume
fields not needed:
edition, number

**Comment by anlausch** [comment] 2017-11-15 07:47
This should be in general quite fast to implement. Could you provide a mapping similar to the two above for each of the type that we need given in the OpenCitations meta data model? This is basically the information I am missing in order to properly deal with the different types. Thanks

**Comment by lgalke** [comment] 2017-11-16 08:22
Sounds good, please wait with deployment until noon. How do we handle the three Input types then? Monograph would stay the Same, Journal should be Most likely Journal Article and collection ist semantically 'In collection', correct? We would also need a mapping for that.Am 16.11.2017 09:07 schrieb anlausch <notifications@github.com>:I have now a version ready in which I only use the OpenCitations/ Crossref types [1]. locdb/loc-db@f49306e
The problem is that deploying this version will break interface with the front end because there is, for example, no resourceType 'COLLECTION' anymore. @lgalke Is it ok to put it online?
[1] https://figshare.com/articles/Metadata_for_the_OpenCitations_Corpus/3443876 (page 2)

**Comment by anlausch** [comment] 2017-11-16 08:26
I think that collection should be mapped to different types, e.g., Book Chapter or Proceedings article. Could someone of the librarians check this? Thanks.

**Comment by lgalke** [comment] 2017-11-16 09:11
- [ ] Book chapter (in *Book*)
- [ ] Book Track (in *Book*?)
- [ ] Component (???)
- [ ] Dataset
- [ ] Dissertation
- [ ] Proceedings article (in *Proceedings*)
- [ ] Standard (in *Standard series*)
- [ ] Report (in *Report series*)
- [ ] Reference Entry (in *Reference book*)
- [ ] Journal Article (in *Journal*, *Journal Issue* or *Journal Volume*)

These are the possible values for non-container resources.

**Comment by kleinann** [comment] 2017-11-24 18:08
In theory, a collection (= a book with parts that can have their own refernce lists) could be "Edited book", "Proceedings" or "Reference book".
For the upload of new resources, I'd prefer to use only "Edited book", and for the parts, only "Book chapter". Still, if we have the resource in our system already because it has been cited by another resource processed before, and the citation data came from Crossref, it can have a different resource type.
What would happen then?

**Comment by kleinann** [comment] 2017-11-24 18:18
Possible relations between resource types are:
Monograph
•	Is part of: Book series, book set
•	Has part: book chapter, book part, book section, book track, component

Edited book
•	Is part of: Book series, book set
•	Has part: book chapter, book part, book section, book track, component

Book series
•	Has part: monograph, edited book, book set, book

Book set (=Gesamtaufnahme eines mehrbd. Werks)
•	Has part: monograph, edited book, book
•	Is part of: book series

Book chapter
•	Is part of: monograph, edited book, book

Book section
•	is part of: monograph, edited book, book

Book part
•	is part of: monograph, edited book, book

Book track 
•	Is part of: monograph, edited book; book

Component: 
•	Is part of: monograph, edited book; book

Dissertation

Proceedings article
•	Is part of: Proceedings

Proceedings
•	Is part of: Book series, book set (Not clear if that's conform with the OpenCitations model)
•	Has part: Proceedings article

Journal article
•	Is part of: Journal issue, journal volume, journal

Journal Issue (Heft)
•	Is part of: Journal volume, Journal
•	Has part: journal article

Journal Volume (Band)
•	Is part of: journal
•	Has part: journal issue, journal article

Journal
•	Has part: Journal volume, Journal Issue, Journal Article

Dataset

Report
•	Is part of: Report series

Book
•	Is part of: Book series, book set
•	Has part: book chapter, book part, book section, book track, component

Reference book
•	Has part: Reference entry

Reference entry
•	Is part of: Reference book

Standard
•	Is part of: Standard series

Standard series
•	Has part: Standard

**Comment by lgalke** [comment] 2017-11-30 23:45
That list is great. So apart from the relations, the plan is to make all OpenCitations resource types available (for the drop-down in the resource-edit form). Am I correct?

**Comment by kleinann** [comment] 2017-12-04 08:55
Yes, exactly. Of course, if the type is already specified in the data source (will be the case for Crossref), it should be set automatically.

**Comment by lgalke** [comment] 2017-12-14 09:38
Now all OCC types are available in the drop-down for new resources. e6ded85

**Comment by lgalke** [comment] 2017-12-14 09:50
The 3 three input types `MONOGRAPH`, `JOURNAL`, and `COLLECTION` are still the same but `COLLECTION` now silently maps to `book chapter`. As the type selection here is crucial for the following behaviour of the system, we should maybe keep them seperate from the full possibilities of the OCC model.

The current semantics are
- `COLLECTION` ➡️ A resource in some arbitrary collection.
- `JOURNAL` ➡️ An **electronic** resource in some arbitrary collection.
- `MONOGRAPH` ➡️ A stand-alone resource.

Maybe its best to relabel them, so that the seperation of the **input types** from **resource types** becomes more clear? @kleinann @zuphilip Whats your take on this?

**Comment by zuphilip** [comment] 2017-12-14 17:22
@kleinann The list of all OC types is quite huge to select one of them. Some types will never been choosen for resolving or todo, e.g. Volume, Issue, Standards series, and some types we might not want to use because they are difficult to differentiate, e.g. edited book, book set.

![type-list](https://user-images.githubusercontent.com/5199995/34003377-6dce7138-e0f5-11e7-9022-10d56a3abb30.png)

What list would make sense for the resolving step? Can we shorten it to something like:
* journal article
* book chapter
* book
* dissertation
* report
* ?

@lgalke I don't understand all consequences, but renaming these three things could be the right thing to do for the input side. They might more be reflecting the workflow or the semantics you give above, maybe something like
* PRINT: PART
* ELECTRONIC JOURNAL
* PRINT: STANDALONE

but this are just some first ideas...

**Comment by kleinann** [comment] 2017-12-18 16:02
For new resources, the complete list would be ok for me, because you can move around quite comfortably by typing the first letter of the word (f. ex. "j" --> journal article; "m" --> monograph).

Input types: Looking at the entities that we want to process, it would probably be "Monograph", "Book Chapter" and "Journal article" (all of which can be electronic or print). The metadata that we reference during the input process can of course contain data that belongs to the container level, not the resource level (f.ex. journal issue in our new data model). But I'm not sure if I get your point here, @lgalke Why do you think it would be important for the operator to make a distinction between input types and resource types?

**Comment by LauraErhard** [comment] 2017-12-18 17:32
The complete list is another area where we have to scroll through, but the jumping really helps to make it less annoying. Thus I am okay with the complete list.

**Comment by SylviaZander** [comment] 2017-12-19 10:26
I would prefer a shorter list and take out the terms that we definitely do not need (see suggestion zuphilipp). But typing the first letters is definitely more comfortable than scrolling!

**Comment by lgalke** [comment] 2017-12-19 14:14
For now the three input types have a clear mapping as you pointed out @kleinann .
However, when we want to be a little more generic with the software, people may start asking why they are not allowed to enter the DOI/PPN of a monograph (and not a journal), or they want to upload a paper that is part of printed conference proceedings. To anticipate those issues, we could label the three input variants sligthly more generic, e.g., exactly the way @zuphilip suggested. Plus, it makes clear that it does not determine the type of the resource itself but the way how the resource will get processed.

**Comment by kleinann** [comment] 2017-12-22 14:54
Ok, I see. Wouldn't it be enough then to specify the type of identifier (DOI, SWB_PPN etc.) without naming the input type? The type of identifier determines the place where to look for the complete metadata, and this contains the publication type and the print/electronic marker (or, if the identifier is a DOI, the resource is always electronic). What else do we have to know at this point in order to process the input?

**Comment by lgalke** [comment] 2018-03-19 13:57
Hey @

**Closed by lgalke** 2018-03-19 13:57 UTC
Labels: enhancement, model
