### ISSUE TITLE
Committing "new resource from reference metadata" Bug

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#222] opened 2018-01-09 14:08 UTC
I tried to commit a new resource from the reference metadata but it doesn't work.
![commit bug](https://user-images.githubusercontent.com/32642653/34724644-d8521a38-f54e-11e7-88f3-f01a88ba7a83.png)

**Comment by lgalke** [comment] 2018-01-09 14:57
Thanks for reporting this. Will fix as soon as possible.

**Comment by lgalke** [comment] 2018-01-09 16:10
Fixed by 0c3ffd5796f35fbd425079407f66609805551283

**Comment by LauraErhard** [comment] 2018-01-09 16:13
Thanks for your quick work, but now I get this message:
![commit bug_notfixed](https://user-images.githubusercontent.com/32642653/34730668-5fcfc198-f560-11e7-9fd7-097543cae205.png)

**Comment by lgalke** [comment] 2018-01-09 16:47
Need to double check (latest) tomorrow morning.

**Comment by lgalke** [comment] 2018-01-09 17:07
Could not reproduce it for now, I only achieved
```
Something went wrong during commit: 400 - Bad Request The br already exists (entry with exactly the same fields is in the database, use put endpoint).
```
after I tried to commit to the same external resource twice. The `JSON.parse` error is quite suspicious.
Could you try to reproduce the problem and supply the detailed error description from the console log?

**Comment by LauraErhard** [comment] 2018-01-09 19:12
I checked again and it only happens with the reference "Gangl M: Unemployment Benefits as a Search Subsidy: New Evidence on Duration and Wage Effects of Unemployment Insurance 2002" (see below)
![commit_bug](https://user-images.githubusercontent.com/32642653/34737754-513b59c8-f577-11e7-87a6-79391b3f64b4.png)
It looks like the committing worked but I don't see the refences category on the left side and the box stays red, therefore I assumed it didn't commit right?! I committed it a few times therefore it maybe created dublicates. But the internal search doesn't show any entries with this title. Maybe you can check in the backend if there are entries with this title?!

**Comment by LauraErhard** [comment] 2018-01-26 12:31
The same happened with the reference: "Gilroy, P.: The Black Atlantic: Modernity and double consciousness 1993"
![json error](https://user-images.githubusercontent.com/32642653/35439892-2cdbe98e-029d-11e8-8e24-6bee07852ff3.png)

**Comment by lgalke** [comment] 2018-01-26 15:08
We need to check, what exactly causes it. Could be anywhere in the communication between front- and back-end. These json.parse issues arise when the backend sends some HTTP error code, where a JSON reply was expected. We need to find out what went wrong in the first place. Thanks for reporting those spurious examples!

**Comment by LauraErhard** [comment] 2018-02-21 16:21
It happened again with the reference: "DOI: 10.1080/00221546.2006.11778948" from American Behavioral Scientist: Is Developmental Education Helping Community College Students Persist? A Critical Review of the Literature
![json bug_2018-02-21](https://user-images.githubusercontent.com/32642653/36491610-722693fc-172b-11e8-85a4-2c13db4c1b46.png)

**Comment by lgalke** [comment] 2018-03-08 12:04
This is very interesting. So it is possible, that these are "just" HTTP errors, which can always occur in web communication for reasons we don't have control of. Whenever, I encounter this problem, I will still try to trace it further down.

**Comment by lgalke** [comment] 2018-03-08 14:36
Among all the examples, was it always in cases of `From reference meta-data`?

**Comment by LauraErhard** [comment] 2018-03-09 07:11
It happened with `External suggestions`, both with Crossref and SWB suggestions. I believe it never happened with an `Internal suggestion` or a `New resource from reference metadata`.

**Comment by lgalke** [comment] 2018-03-09 09:11
I assume that this is caused by some *missing values* in the suggestion, which neither the back-end nor the front-end fills with empty values `""`. Then the database verification fails. We will keep this in mind while adapting to the new data model. #243

**Comment by SylviaZander** [comment] 2018-03-14 10:05
It happend again with an external suggestion (SWB). I can't commit it with the reference
![json](https://user-images.githubusercontent.com/32641017/37395862-97f16556-2777-11e8-8396-91d64f304fe2.PNG)


https://screenshots.firefox.com/2lAz6qzeRBgKki2j/locdb.bib.uni-mannheim.de

**Closed** 2018-03-19 14:06 UTC
Labels: bug, question
