### ISSUE TITLE
Error 418 occured

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#208] opened 2017-11-30 14:37 UTC

**Comment by anlausch** [comment] 2017-11-30 14:47
Any description of where and when?

**Comment by zuphilip** [comment] 2017-11-30 18:02
It occurred once during testing today. I think we tried to commit a link CC @kleinann . Then this error in browser alert window appeared.

**Comment by lgalke** [comment] 2017-11-30 23:11
I'm a teapot... https://httpstatuses.com/418 LOCDB is now featuring the famous easter egg 🥇

**Comment by lgalke** [comment] 2017-11-30 23:16
It can occur inside the whole commit logic.

1. If `resource` does not have LOCDB identifier yet (external or new local resource), push BR
2. If entry already has a `references` link, remove it.
3. Add link from `entry` to `resource`

Could you supply a more detailed description of the situation, regarding the above commit logic?

**Comment by kleinann** [comment] 2017-12-01 08:58
I think the error occurred when we deleted a BR that was linked to a BE, and then tried to re-link the same BE to a new BR. But I cannot reproduce the error today. What happens now is: The link in the BE is not deleted and links to an empty resource (a box without content). Even after deleting it manually, it's not possible to create a new link, and it's not possible to create a new BR from the BE data.

**Comment by kleinann** [comment] 2017-12-01 08:58
![grafik](https://user-images.githubusercontent.com/33151732/33475308-3d31b976-d67e-11e7-8abc-709e5f02f511.png)

**Comment by kleinann** [comment] 2017-12-01 08:59
See the empty box under "Currently references".

**Comment by lgalke** [comment] 2017-12-01 10:05
Okay, good to have this pointed out. Apparently deleting the resource does not delete the reference to it. (See long-term issue #60). For now I could just intercept the error, when the resource of the references field is non-existent.

**Comment by lgalke** [comment] 2017-12-01 11:06
The teapot issue is now resolved, the error is caught. The behaviour on delete still leads to an inconsistent view, but this will be tackled after the redesign.

**Comment by LauraErhard** [comment] 2017-12-05 14:28
It happened again:
I wanted to `commit link` a crossref reference. (prod)
DOI: 10.1177/1468796807080237
1. the references field was not filled before
2. I selected a crossref external suggestion
3. 
`400 - Bad Request {"message":"Validation errors","errors":[{"code":"INVALID_REQUEST_PARAMETER","errors":[{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","32","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","31","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","29","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","28","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","27","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","26","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","25","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","24","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","23","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","22","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","21","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","19","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","18","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","17","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","16","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","15","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","14","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","12","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","9","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","8","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","7","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","6","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","5","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","4","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","3","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","2","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","1","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","0","identifiers","0"]}],"in":"body","message":"Invalid parameter (bibliographicResource): Value failed JSON Schema validation","name":"bibliographicResource","path":["paths","/bibliographicResources","post","parameters","0"]}]}`

**Comment by lgalke** [comment] 2017-12-05 19:53
As assumed it happens when there is an identifier present that is missing a literalvalue in the suggested resource. @anlausch will you fix? I could also impose some brute force fix, but it would be probably cleaner, when the *suggested resource* was already valid wrt the Data model in the first place.Am 05.12.2017 8:28 vorm. schrieb LauraErhard <notifications@github.com>:It happened again:
I wanted to commit link a crossref reference. (prod)
DOI: 10.1177/1468796807080237
the references field was not filled beforeI selected a crossref external suggestion
400 - Bad Request {"message":"Validation errors","errors":[{"code":"INVALID_REQUEST_PARAMETER","errors":[{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","32","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","31","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","29","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","28","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","27","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","26","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","25","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","24","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","23","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","22","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","21","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","19","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","18","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","17","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","16","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","15","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","14","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","12","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","9","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","8","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","7","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","6","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","5","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","4","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","3","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","2","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","1","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","0","identifiers","0"]}],"in":"body","message":"Invalid parameter (bibliographicResource): Value failed JSON Schema validation","name":"bibliographicResource","path":["paths","/bibliographicResources","post","parameters","0"]}]}

**Comment by anlausch** [comment] 2017-12-07 11:05
Can you check again?

**Comment by kleinann** [comment] 2017-12-07 11:19
I tried with several Crossref records from the references of Acta Sociologica
Conflict in the world polity - neo-institutional perspectives, and it worked. @LauraErhard could you go on testing? - Thanks, Anne, for the quick fix.

**Comment by SylviaZander** [comment] 2017-12-07 13:46
When we started with the real data production yesterday, the 418 error always occurred when we wanted to link an article from the list of references to a crossref hit (after editing when saving)
e.g.  DOIs 10.1017/s0020818304582024
10.2307/2095101
10.1177/1749975507082052
( references of Acta Sociologica: Conflict in the world polity - neo-institutional perspectives)

But when we created a new resource (since no matching hits were offered via the Querysearch) there was no error message when saving.

I just linked some new references and it seems to work now!
Thanks!

**Comment by lgalke** [comment] 2017-12-11 09:14
Seems to be resolved for now.

**Comment by SylviaZander** [comment] 2017-12-11 09:15
The Error occured again. This time with the SWB suggestion: 
![418-error](https://user-images.githubusercontent.com/32641017/33823626-16cc9fa4-de5c-11e7-9745-cefbd2b7ef32.png)

**Comment by lgalke** [comment] 2017-12-11 09:18
@anlausch ?

**Comment by anlausch** [comment] 2017-12-11 10:49
When looking at what is happening here, I am encountering several issues:
1. The error code 418 is misleading. @lgalke I think maybe one should either inform us that 418 corresponds to 400 (if this is always the case) or change it. I was a bit confused by that. :)
2. The resource is saved with status external. That should not be the case, right (but this is not the problem here)?
3. I tried to reproduce it in dev and there the error occurs there because you are sending null values in the name string. ("Expected type string but found type null"). If you change that, it should work.

**Comment by lgalke** [comment] 2017-12-11 11:48
> The error code 418 is misleading. @lgalke I think maybe one should either inform us that 418 corresponds to 400 (if this is always the case) or change it. I was a bit confused by that. :)

That's right, it was actually just a placeholder error message. It is now replaced by the more verbose `"Something went wrong during commit: " + err`.

 >The resource is saved with status external. That should not be the case, right (but this is not the problem here)?

If the resource does not have an `_id` property yet (i.e. is `EXTERNAL`) it gets `POST`ed to `/bibliographicResource`. Then the response is taken **as is** (unmodified status) and used as target for `/updateTargetBibliographicResource`. 

> I tried to reproduce it in dev and there the error occurs there because you are sending null values in the name string. ("Expected type string but found type null"). If you change that, it should work.

Initially, the process above starts with some unmodified resource that is obtained by `/getExternalSuggestionsByQueryString`. For the identifiers, I already noticed the problem that some of the suggestions have `scheme='DOI'` but no `literalValue`. Is it possible that there is a similar issue with the `namestring` of authors? @anlausch

**Comment by anlausch** [comment] 2017-12-11 13:47
> For the identifiers, I already noticed the problem that some of the suggestions have scheme='DOI' but no literalValue. Is it possible that there is a similar issue with the namestring of authors? @anlausch

I checked it for some examples and in the suggestions, usually, the name string property is not given at all if not set.

**Comment by lgalke** [comment] 2017-12-11 13:51
You mean it gets lost in the front-end, or it is already not present in the suggestions? (the `namestring` property itself)?

**Comment by anlausch** [comment] 2017-12-11 14:18
It is not present in the suggestions. https://locdb.bib.uni-mannheim.de/locdb-dev/getExternalSuggestionsByQueryString?query=Minorities%2520at%2520Risk:%2520A%2520Global%2520View%2520of%2520Ethnopolitical%2520Conflicts&threshold=0.2

**Comment by LauraErhard** [comment] 2017-12-11 14:39
Same 418 Error (with SWB suggestion), but now I get a different console message:
![418 error](https://user-images.githubusercontent.com/32642653/33836332-6c0def5e-de89-11e7-80c8-8648d304a34d.png)

`400 - Bad Request {"message":"Validation errors","errors":[{"code":"INVALID_REQUEST_PARAMETER","errors":[{"code":"INVALID_TYPE","params":["string","null"],"message":"Expected type string but found type null","path":["contributors","2","heldBy","nameString"]}],"in":"body","message":"Invalid parameter (bibliographicResource): Value failed JSON Schema validation","name":"bibliographicResource","path":["paths","/bibliographicResources","post","parameters","0"]}]}`

**Comment by lgalke** [comment] 2018-04-13 11:50
In this case the validation failed because of an empty `nameString`...

**Comment by anlausch** [comment] 2018-04-25 15:12
I close this issue now due to missing activity. It seems like the issue is solved. If not feel free to open again.

**Closed by anlausch** 2018-04-25 15:12 UTC
Labels: back-end, enhancement, front-end
