### ISSUE TITLE
Wrong publication type for external suggestions

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#288] opened 2018-05-08 13:58 UTC
Journal articles found in external suggestions are shown in the frontend as Journal issues. Example: 10.1080/00313830802184608, 10.1177/0001699307083981.

**Comment by lgalke** [comment] 2018-05-14 07:56
Will double-check whether this problem is caused by the front-end, but we typically select the child's resource type (with respect to our 2-level parent-child flattened hierarchy) for display, which should be then journal article. Is it possible, that the extraction emits already journal issue instead of article in the first place @anlausch ?

**Comment by anlausch** [comment] 2018-05-15 07:11
The /saveResource call with these DOIs returns an Array with the JOURNAL_ARTICLE at position 0 and JOURNAL_ISSUE as parent at position 1. This should be correct. Or, is this different from what you expect?

**Comment by lgalke** [comment] 2018-05-15 07:26
@kleinann is concerned about the results from external suggestions. There, we expect the similar format of a tuple of [parent, child] or [child] if there is no parent.

**Comment by anlausch** [comment] 2018-05-15 07:35
I cannot see any problem there, it is just the other way round. The resources are nested according to this structure. Searching for `10.1080/00313830802184608` returns an array containing `[JOURNAL_ARTICLE, JOURNAL_ISSUE]`, exactly as in `/saveResource`. I am really sorry in case I didn't communicate this properly. This will be added to the documentation.

**Comment by lgalke** [comment] 2018-05-15 08:08
Oh maybe I just mixed it up in here, @chah3d is just checking whether we mix something up at some point.

**Comment by lgalke** [comment] 2018-05-15 13:54
Should be resolved by fcb8924 and also deployed. Next, we are targeting the propert display of container resources with respect to the hackmd file.

**Closed by lgalke** 2018-05-15 13:54 UTC
