### ISSUE TITLE
Change to newly released angular-cli v1.0.0

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#1] opened 2017-04-08 12:31 UTC
The version 1.0.0 was released some days ago: https://github.com/angular/angular-cli/releases

Can we switch to that version?

**Comment by lgalke** [comment] 2017-04-09 17:34
Of course, I'd just prefer to wait until Wednesday with any version upgrades.

**Comment by zuphilip** [comment] 2017-04-11 19:59
Maybe we could even try out this service: https://github.com/integration/greenkeeper

**Comment by lgalke** [comment] 2017-04-12 08:36
Looks great! Thanks for the pointer.

**Comment by zuphilip** [comment] 2017-04-12 13:31
Hm... The PR is now merged but the badge indicates that greenkeeper is not active. Can it be that we need also a continuous integration? I would suggest Travis CI or Circle CI which should be quite easy to add given your structure and that you have tests already. Let me know what you think about CI...

**Comment by lgalke** [comment] 2017-04-12 13:35
I only merged the new branch to update dependencies, but there was still no PR from greenkeeper. I also had a look into Travis CI already. I'd give it a try.

**Comment by lgalke** [comment] 2017-04-12 13:49
In `.travis.yml` I invoked `npm test` which in turn invokes `ng test`. However the test suite based on Karma used by `ng test` is continuous and also tries to open up a browser. Unfortunately, we would need to put some more effort in the integration of travis.

**Comment by zuphilip** [comment] 2017-04-12 19:47
I tried some things to fix it, see https://github.com/locdb/locdb-frend/pull/4, but it is not yet working...

**Comment by lgalke** [comment] 2017-04-12 21:57
This is probably also caused by the tests themselves, since most of them are default ones and some just fail depending on the build target (es5 vs es6). I tried to fix it by adding `@types/core-js` and the appropriate entries in `ts-config.json` but it did not help either. I will have a look at the test themselves, soon.

**Comment by lgalke** [comment] 2017-04-12 23:11
As assumed, the default tests are just borken. See [here](https://github.com/angular/quickstart/issues/192).

**Comment by lgalke** [comment] 2017-04-13 08:20
I can assert that the test progress itself works now as expected. Explicit imports and declarations of the AppModule for the testcase were required.

For now the default test cases need to be adapted to something more reasonable. :+1:

**Comment by lgalke** [comment] 2017-04-20 07:40
Since the update to most recent `angular-cli` version is merged already, I will close this issue and open another one for fixing the specs.

**Closed by lgalke** 2017-04-20 07:40 UTC
